run:
	./testarg Huey Dewey Louie
	
runB:
	./testargB 6.2 -8 2.0
	
runC:
	./testargC 6.2 -8 2.0
	
compile:
	gcc -Wall -o testarg -g testarg.c
	
compileB:
	gcc -Wall -o testargB -g testargB.c
	
compileC:
	gcc -Wall -o testargC -g testargC.c

clean:
	rm -f testarg
	rm -f testargB
	rm -f testargC
